version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    # 環境変数をファイルから読み込む
    env_file:
      - .env
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    # 変更点
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e production
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    # 環境変数をファイルから読み込む
    env_file:
      - .env
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: "node:14-alpine"
    user: "node"
    volumes:
      - ./frontend:/frontend
    command: "yarn start"
    ports:
      - "9999:9999"
    depends_on:
      - backend
