FROM ruby:3.0.0-alpine

RUN apk update
RUN apk add --no-cache --virtual .build-deps gcc make musl-dev build-base libxml2-dev libxslt-dev bash
RUN gem install solargraph
RUN solargraph download-core

WORKDIR /app

# Create Gemfile
RUN bundle init
RUN echo "gem 'solargraph'" >> Gemfile
# gem のインストール先を設定
RUN mkdir /bundle
RUN bundle config set --local path './bundle'
RUN bundle install

EXPOSE 7658
