FROM ruby:3.0.0-alpine

RUN apk update \
  && apk add --no-cache --virtual .build-deps gcc make musl-dev build-base libxml2-dev libxslt-dev bash \
  && gem install solargraph \
  && solargraph download-core

WORKDIR /app

# Create Gemfile
RUN bundle init \
&& echo "gem 'solargraph'" >> Gemfile \
&& mkdir /bundle \
&& bundle config set --local path './bundle' \
&& bundle install

EXPOSE 7658
